In [1]:
#importing the necessary libraries
import numpy as np    # linear algebra
import pandas as pd   # data processing/feature engineering

In [2]:
#importing datasets 
dataset=pd.read_csv('dataset.csv')
preddata=pd.read_csv('prediction.csv')

In [3]:
#dividing the training dataset into x_test,y_test,x_train,y_train
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,9].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x.shape

(900, 9)

In [4]:
#replacing the missing values in x_train
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x_train[:, 0:9])
x_train[:, 0:9] = imputer.transform(x_train[:, 0:9])

In [5]:
#replacing the missing values in x_train
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x_test[:, 0:9])
x_test[:, 0:9] = imputer.transform(x_test[:, 0:9])

In [6]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
y_pred=regressor.predict(x_test)

In [15]:
y_pred

array([ 9301.4050874 ,  9356.02156164,  8701.82742152,  9086.45162861,
        9311.11951415,  8451.70328424,  8875.25119193,  8322.10531988,
        7774.73480293,  7926.04438232,  8484.24138348,  9042.47021511,
        9349.34914152, 10275.46277937,  8220.567704  ,  9884.4722423 ,
        7559.53692289,  9935.11949099,  8154.74722793,  7491.03482418,
        7935.18771941,  9619.74776404,  8910.39192523,  8939.57511015,
        8633.40890069,  9977.24107989,  8367.92130994,  9277.15267536,
        9717.98224904,  8613.94356818,  8300.20307673,  9495.19071442,
        8454.28163327, 10869.50379527,  8704.65375097,  8834.24617491,
        9981.4715397 ,  8618.67494868,  9305.39534331,  8512.44153432,
       11005.74900926,  9434.4195439 ,  8554.19732173,  9031.79661261,
       10016.12513706,  9150.5502564 ,  9319.72360575,  8414.16581063,
        9351.70878781,  9528.6971253 ,  8785.93351308,  8091.87844642,
        8850.99544964,  9991.89620605,  9055.41046563,  8308.13543595,
      

In [16]:
(y_test)

array([ 9517.1046336 ,  9779.63911229,  8842.03843299,  9018.13945709,
        8859.50005198,  8865.9948426 ,  9486.44321308,  8574.76390133,
        7501.47234909,  7450.00391551,  8873.15985377,  9007.82130439,
        9713.45134992, 10621.12964356,  8494.59595225, 10178.07277714,
        6879.44994141,  9643.74614733,  8513.94586139,  7070.55541878,
        8186.02001918,  9938.64470985,  8861.87592578,  8872.61886961,
        9045.38058375,  9421.01918137,  8688.72109415,  9931.68140915,
        9666.52457901,  8618.21672473,  7483.98336733,  8988.15786035,
        8167.51920318, 10456.41770327,  8601.38606278,  8411.13278985,
       10056.4100952 ,  8747.90833409,  9168.57314223,  8415.11327199,
       10541.68854304, 10114.76173045,  8920.92573014,  8994.32712972,
        9931.38070972,  9109.70856251,  9208.00678551,  7998.16441607,
        9470.0033031 ,  9573.3620957 ,  8202.45898227,  7823.48059286,
        8842.66945793, 10205.97150415,  9722.18389348,  8205.9999755 ,
      

In [17]:
  abs_error = np.abs(y_pred - y_test)
  sum_abs_error = np.sum(abs_error)
  mae = sum_abs_error / y_test.size

In [18]:
#comparing y_pred and y_test
mae

301.0501867982655

In [19]:
#building the model using backward elimination
import statsmodels.api as sm
#to add b0
x=np.append(arr=np.ones((900,1)).astype(int), values=x, axis=1)

In [20]:
x[0]

array([1.00000000e+00, 1.00000000e+00, 7.54760017e+00, 1.51260787e-01,
       5.57132466e+02, 3.54008599e+02, 3.01028697e-01, 5.52825943e+01,
       9.63521168e+03, 2.00000000e+00, 1.00000000e+00])

In [21]:
#for removing unnec feature columns
x_opt=x[:,[0,1,2,3,4,5,6,7,8,9]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.829
Model:                            OLS   Adj. R-squared:                  0.828
Method:                 Least Squares   F-statistic:                     540.6
Date:                Fri, 26 Jun 2020   Prob (F-statistic):               0.00
Time:                        05:33:46   Log-Likelihood:                -6554.9
No. Observations:                 900   AIC:                         1.313e+04
Df Residuals:                     891   BIC:                         1.317e+04
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        469.5907    201.491      2.331      0.020      74.138     865.043
x1           469.5907    201.491      2.331      0.020      74.138     865.043
x2            14.7312      4.123      3.573      0.000       6.640      22.823
x3           224.8903     40.891      5.500      0.000     144.636     305.145
x4             1.0342      0.041     25.375      0.000       0.954       1.114
x5             0.0172      0.101      0.170      0.865      -0.181       0.216
x6         -1951.7158     41.570    -46.950      0.000   -2033.303   -1870.129
x7             0.8195      0.415      1.977      0.048       0.006       1.633
x8             0.9949      0.042     23.661      0.000       0.912       1.077
x9          -523.0917     15.095    -34.654      0.000    -552.717    -493.466
==============================================================================
Omnibus:                       12.172   Durbin-Watson:                   2.073
Prob(Omnibus):                  0.002   Jarque-Bera (JB):                8.082
Skew:                          -0.080   Prob(JB):                       0.0176
Kurtosis:                       2.564   Cond. No.                     1.77e+19
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.61e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [22]:
#removed 4th column
x_opt=x[:,[0,1,2,3,5,6,7,8,9]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.706
Model:                            OLS   Adj. R-squared:                  0.703
Method:                 Least Squares   F-statistic:                     305.6
Date:                Fri, 26 Jun 2020   Prob (F-statistic):          6.36e-232
Time:                        05:33:46   Log-Likelihood:                -6799.6
No. Observations:                 900   AIC:                         1.362e+04
Df Residuals:                     892   BIC:                         1.365e+04
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        803.4010    263.747      3.046      0.002     285.764    1321.038
x1           803.4010    263.747      3.046      0.002     285.764    1321.038
x2            14.8342      5.408      2.743      0.006       4.220      25.448
x3           251.6608     53.622      4.693      0.000     146.420     356.902
x4            -0.0754      0.133     -0.569      0.570      -0.336       0.185
x5         -1905.2031     54.478    -34.972      0.000   -2012.123   -1798.284
x6             0.4328      0.543      0.796      0.426      -0.634       1.499
x7             0.9785      0.055     17.741      0.000       0.870       1.087
x8          -519.0957     19.800    -26.217      0.000    -557.956    -480.236
==============================================================================
Omnibus:                       11.586   Durbin-Watson:                   1.956
Prob(Omnibus):                  0.003   Jarque-Bera (JB):                7.497
Skew:                          -0.049   Prob(JB):                       0.0236
Kurtosis:                       2.564   Cond. No.                     2.54e+19
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.27e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [23]:
x_opt=x[:,[0,1,2,3,5,6,7,8]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.479
Model:                            OLS   Adj. R-squared:                  0.475
Method:                 Least Squares   F-statistic:                     136.8
Date:                Fri, 26 Jun 2020   Prob (F-statistic):          8.99e-123
Time:                        05:33:47   Log-Likelihood:                -7056.7
No. Observations:                 900   AIC:                         1.413e+04
Df Residuals:                     893   BIC:                         1.416e+04
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -237.2307    346.756     -0.684      0.494    -917.782     443.321
x1          -237.2307    346.756     -0.684      0.494    -917.782     443.321
x2            14.1485      7.192      1.967      0.049       0.033      28.264
x3           292.3404     71.281      4.101      0.000     152.442     432.239
x4            -0.1059      0.176     -0.600      0.549      -0.452       0.240
x5         -1811.5181     72.293    -25.058      0.000   -1953.401   -1669.635
x6            -0.6435      0.721     -0.893      0.372      -2.058       0.771
x7             1.0894      0.073     14.897      0.000       0.946       1.233
==============================================================================
Omnibus:                        4.692   Durbin-Watson:                   1.949
Prob(Omnibus):                  0.096   Jarque-Bera (JB):                4.691
Skew:                          -0.154   Prob(JB):                       0.0958
Kurtosis:                       2.827   Cond. No.                     2.92e+19
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.59e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [24]:
x_opt[0]

array([1.00000000e+00, 1.00000000e+00, 7.54760017e+00, 1.51260787e-01,
       3.54008599e+02, 3.01028697e-01, 5.52825943e+01, 9.63521168e+03])

In [25]:
x[0]

array([1.00000000e+00, 1.00000000e+00, 7.54760017e+00, 1.51260787e-01,
       5.57132466e+02, 3.54008599e+02, 3.01028697e-01, 5.52825943e+01,
       9.63521168e+03, 2.00000000e+00, 1.00000000e+00])

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_opt,y,test_size=0.2,random_state=0)

In [27]:
 from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x_train[:, 0:9])
x_train[:, 0:9] = imputer.transform(x_train[:, 0:9])

In [28]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x_test[:, 0:9])
x_test[:, 0:9] = imputer.transform(x_test[:, 0:9])

In [29]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
y_pred=regressor.predict(x_test)

In [31]:
y_pred

array([ 9242.35296131,  9464.91086405,  8988.07738156,  9500.21445356,
        9379.80274191,  8843.29074697,  8416.96177054,  7963.16920567,
        8810.94510471,  8854.03412554,  8358.84620631,  8324.49679605,
        9745.96073361,  9770.59330409,  9032.67444003,  9235.48981004,
        8044.87425316,  9200.53211558,  7776.37924073,  7897.66586276,
        8470.57534339,  9617.60344679,  9157.53613833,  9358.64144187,
        8686.5837564 ,  9584.6005242 ,  8457.00571861,  8493.20406684,
        9938.44352049,  8265.21305993,  8714.97371398,  9640.50019396,
        9065.99893754,  9950.96350984,  8923.26424499,  8983.81874932,
        9710.0501128 ,  8409.10851467,  8911.43013028,  8484.74642895,
       10323.34693097,  9986.08043356,  8758.9486178 ,  9196.52336734,
        9478.77600753,  8647.94711019,  9344.77039149,  8934.54135139,
        8513.92935085,  9522.98375315,  8785.31292474,  8044.85709377,
        8870.92708361,  9672.72666218,  9737.59715429,  9036.62880793,
      

In [32]:
  abs_error = np.abs(y_pred - y_test)
  sum_abs_error = np.sum(abs_error)
  mae = sum_abs_error / y_test.size

In [33]:
#error remains almost same 
mae

491.70879481013833

In [34]:
dataset

0         1           2  ...    7    8        target
0    7.547600  0.151261  557.132466  ...  2.0  1.0   9461.469590
1    3.140491  0.794497  837.116189  ...  2.0  5.0  10257.271938
2    2.064447  0.236500  313.757354  ...  1.0  5.0   8719.214483
3    9.099262  0.453953  661.409826  ...  3.0  2.0   9165.197338
4    5.264564  0.683869  344.154511  ...  2.0  1.0   9458.427537
..        ...       ...         ...  ...  ...  ...           ...
895  1.488893  0.516765  519.122916  ...  3.0  4.0   7741.681561
896  3.623385  0.192006  296.631532  ...  3.0  1.0   8794.950815
897  0.251811  0.049025  992.634520  ...  3.0  5.0   9130.681938
898  7.495874  0.168602  898.795067  ...  2.0  1.0   8846.715266
899  6.314877  0.186995  968.025445  ...  2.0  3.0  10375.238911

[900 rows x 10 columns]

In [35]:
#predicted value after removing unnecessay columns 
X_train=dataset.iloc[:,[0,1,2,3,5,6,7,8]].values
Y_train=dataset.iloc[:,9].values

In [36]:
X_test=preddata.iloc[:,[0,1,2,3,5,6,7,8]].values

In [37]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [38]:
y_pred=regressor.predict(X_test)

In [39]:
y_pred

array([ 9746.21086013,  9440.52534788,  9106.50695955,  8365.42057745,
        9971.13107811,  9788.5101548 ,  8136.8694006 , 10198.66982908,
        9714.04688356,  9147.45088215,  8962.36274799, 10113.61148571,
       10186.38577129,  8752.60799447,  8346.45448433,  9196.52499022,
        8684.31071561, 10449.12476436,  8563.38890574,  8857.02014865,
        9355.47801783,  8361.00692519,  9196.73431875,  8565.23036602,
        8913.43753244,  8905.38461298,  9173.89667441,  9652.66746816,
        8556.56865498,  9365.2640947 ,  9013.22750015,  9042.37656695,
        9371.24044617,  9214.01719914, 10097.6236604 , 10336.43554086,
        8674.06037181,  9286.08413881,  8839.1924884 ,  9492.30637933,
        9306.89490481,  8848.55700672,  9095.93549987,  8522.67435605,
        7991.35239459,  9369.22136349,  9095.65895931,  9127.80167756,
        8850.67201804,  9451.93871837,  9436.69629872,  9154.75821213,
        8930.74965292,  8169.20099629,  8855.61561466, 10260.07513199,
      

In [40]:
preddata["Target"]=y_pred

In [41]:
preddata.to_csv('Prediction.csv')