In [311]:
import numpy as np    # linear algebra
import pandas as pd   # data processing/feature engineering
import matplotlib.pyplot as plt       # Data visualization
import seaborn as sns                 # Enhanced Data Visualization
%matplotlib inline
from sklearn.linear_model import LogisticRegression # Logistic Regression Model

In [312]:
dataset=pd.read_csv('challenge2_dataset.csv')
preddata=pd.read_csv('challenge2_prediction.csv')

In [313]:
dataset

1     2     3 Target
0     0.60  0.31  13.0  False
1     0.74  0.33  21.0  False
2     0.54  0.19   NaN   True
3     0.46   NaN   9.0  False
4     0.77  0.15  15.0   True
...    ...   ...   ...    ...
1990  0.80  0.30  22.0  False
1991  0.69  0.22   9.0   True
1992  0.66  0.24  15.0  False
1993  0.46  0.26  11.0  False
1994  0.49  0.22  10.0  False

[1995 rows x 4 columns]

In [314]:
preddata

1     2     3
0    0.74  0.21  22.0
1    0.43  0.15  14.0
2    0.77  0.10  15.0
3    0.57  0.31  15.0
4    0.80  0.31  20.0
..    ...   ...   ...
850  0.80  0.19  19.0
851  0.40  0.15  21.0
852  0.49  0.26  17.0
853  0.63  0.31  14.0
854  0.80  0.21  16.0

[855 rows x 3 columns]

In [315]:
dataset.Target = df.Target.fillna(True)
dataset.iloc[:,3] = dataset.iloc[:,3]*1

In [316]:
dataset

1     2     3  Target
0     0.60  0.31  13.0       0
1     0.74  0.33  21.0       0
2     0.54  0.19   NaN       1
3     0.46   NaN   9.0       0
4     0.77  0.15  15.0       1
...    ...   ...   ...     ...
1990  0.80  0.30  22.0       0
1991  0.69  0.22   9.0       1
1992  0.66  0.24  15.0       0
1993  0.46  0.26  11.0       0
1994  0.49  0.22  10.0       0

[1995 rows x 4 columns]

In [317]:
x_train=dataset.iloc[:,:-1].values
y_train=dataset.iloc[:,3].values

In [318]:
x_test=preddata.iloc[:,:].values


In [319]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x_train[:, 0:3])
x_train[:, 0:3] = imputer.transform(x_train[:, 0:3])

In [320]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x_test[:, 0:3])
x_test[:, 0:3] = imputer.transform(x_test[:, 0:3])


In [321]:
x_train

array([[ 0.6       ,  0.31      , 13.        ],
       [ 0.74      ,  0.33      , 21.        ],
       [ 0.54      ,  0.19      , 16.33316608],
       ...,
       [ 0.66      ,  0.24      , 15.        ],
       [ 0.46      ,  0.26      , 11.        ],
       [ 0.49      ,  0.22      , 10.        ]])

In [322]:
x_test

array([[ 0.74,  0.21, 22.  ],
       [ 0.43,  0.15, 14.  ],
       [ 0.77,  0.1 , 15.  ],
       ...,
       [ 0.49,  0.26, 17.  ],
       [ 0.63,  0.31, 14.  ],
       [ 0.8 ,  0.21, 16.  ]])

In [323]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# x_train=sc.fit_transform(x_train)
# x_test=sc.fit_transform(x_test)

In [324]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [325]:
y_pred=classifier.predict(x_test)

In [326]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,

In [327]:
y_pred = y_pred.astype(bool)

In [328]:
y_pred

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False,  True, False, False,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False,  True, False, False,
       False,  True, False,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
        True, False,

In [329]:
preddata["Target"]=y_pred

In [330]:
preddata.to_csv('Prediction.csv')